# engine/events.py
# ============================================================
# ALL EVENT DATACLASSES — THE DATA CONTRACT BETWEEN MODULES
# Events are the only way modules communicate.
# ============================================================

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class EventType(Enum):
    """
    Enumerates all possible event types in the system.

      MARKET  → Emitted by DataHandler each time a new bar is available.
      SIGNAL  → Emitted by Strategy when it detects a trade setup.
      ORDER   → Emitted by Portfolio after sizing; triggers Execution.
      FILL    → Emitted by Execution after simulating a broker fill.
    """
    MARKET = "MARKET"
    SIGNAL = "SIGNAL"
    ORDER  = "ORDER"
    FILL   = "FILL"


class SignalDirection(Enum):
    """Direction of a trading signal emitted by the Strategy module."""
    LONG       = "LONG"
    SHORT      = "SHORT"
    EXIT_LONG  = "EXIT_LONG"
    EXIT_SHORT = "EXIT_SHORT"


class OrderDirection(Enum):
    """Direction of an order generated by the Portfolio Manager."""
    BUY  = "BUY"
    SELL = "SELL"


@dataclass
class MarketEvent:
    """
    Signals that a new OHLCV bar is available for a symbol.
    One MarketEvent is emitted per symbol per bar.
    """
    event_type: EventType = field(default=EventType.MARKET, init=False)
    timestamp:  datetime          = None
    symbol:     str               = ""
    open:       Optional[float]   = None
    high:       Optional[float]   = None
    low:        Optional[float]   = None
    close:      float             = 0.0
    volume:     Optional[float]   = None
    is_last_bar: bool             = False


@dataclass
class SignalEvent:
    """
    A trade signal generated by a Strategy.
    strength ∈ [0, 1] — signal confidence (1.0 if not computed).
    """
    event_type:  EventType       = field(default=EventType.SIGNAL, init=False)
    timestamp:   datetime        = None
    symbol:      str             = ""
    strategy_id: str             = ""
    direction:   SignalDirection = SignalDirection.LONG
    strength:    float           = 1.0


@dataclass
class OrderEvent:
    """
    An order to buy or sell a specific quantity.
    Always MARKET type in this backtester.
    """
    event_type: EventType          = field(default=EventType.ORDER, init=False)
    timestamp:  datetime           = None
    symbol:     str                = ""
    direction:  OrderDirection     = OrderDirection.BUY
    quantity:   int                = 0
    order_type: str                = "MARKET"
    signal_ref: Optional[SignalEvent] = None


@dataclass
class FillEvent:
    """
    Records the actual simulated execution of an order.
    commission includes brokerage + STT + stamp duty + exchange charges.
    slippage is the INR cost of slippage (informational; already in fill_price).
    """
    event_type:  EventType         = field(default=EventType.FILL, init=False)
    timestamp:   datetime          = None
    symbol:      str               = ""
    direction:   OrderDirection    = OrderDirection.BUY
    quantity:    int               = 0
    fill_price:  float             = 0.0
    commission:  float             = 0.0
    slippage:    float             = 0.0
    order_ref:   Optional[OrderEvent] = None
